# Generated by Django 3.2.6 on 2021-08-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='imagen',
            field=models.URLField(blank=True, null=True, verbose_name='Link de la imagen'),
        ),
    ]
