# Generated by Django 3.2.6 on 2021-08-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quiz_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
