# Generated by Django 3.2.6 on 2021-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('perfil', models.TextField()),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Link de la imagen')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Link de Linkedin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'integrante',
                'db_table': 'integrantes',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Miscelanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='Link de la imagen')),
                ('informe', models.TextField()),
                ('link_informe', models.URLField(verbose_name='Link del informe')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'titulo',
                'db_table': 'titulos',
                'ordering': ['created'],
            },
        ),
    ]
