# Generated by Django 3.2.6 on 2021-08-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_integrante_miscelanea'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Linkedin'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='miscelanea',
            name='link_informe',
            field=models.URLField(verbose_name='Link del informe'),
        ),
    ]
