# Generated by Django 3.2.6 on 2021-08-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ayuda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayuda',
        ),
    ]
