# Generated by Django 3.2.6 on 2021-08-26 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juego', '0002_auto_20210823_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_preguntas', models.IntegerField(blank=True, null=True)),
                ('cantidad_respuestas', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='juego.categoria')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='juego.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'puntuaciones',
            },
        ),
    ]
